version: '3'

services:
#  web_php_nginx_mysql:
#    container_name: web_php_nginx_mysql
#    build: ./base/web_php_nginx_mysql
#    image: web_php_nginx_mysql:latest
#    working_dir: /root/task
#    stdin_open: true
#    tty: true
#    dns:
#        - 8.8.8.8
#        - 1.1.1.1

# Source code
  demo2:
    container_name: demo2
    build: ./2022/web/2
    environment:
      - PORT=8802
    ports:
      - '8802:80'
    working_dir: /root/task
    stdin_open: true
    tty: true
    dns:
        - 8.8.8.8
        - 1.1.1.1
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 30M
        reservations:
          cpus: '0.01'
          memory: 30M

# Javascript
  demo3:
    container_name: demo3
    build: ./2022/web/3
    environment:
      - PORT=8803
    ports:
      - '8803:80'
    working_dir: /root/task
    stdin_open: true
    tty: true
    dns:
        - 8.8.8.8
        - 1.1.1.1
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 30M
        reservations:
          cpus: '0.01'
          memory: 30M

# XSS
  demo4:
    container_name: demo4
    build: ./2022/web/4
    environment:
      - PORT=8804
    ports:
      - '8804:80'
    working_dir: /root/task
    stdin_open: true
    tty: true
    dns:
        - 8.8.8.8
        - 1.1.1.1
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 30M
        reservations:
          cpus: '0.01'
          memory: 30M

# Javascript 3
  demo5:
    container_name: demo5
    build: ./2022/web/5
    environment:
      - PORT=8805
    ports:
      - '8805:80'
    working_dir: /root/task
    stdin_open: true
    tty: true
    dns:
        - 8.8.8.8
        - 1.1.1.1
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 30M
        reservations:
          cpus: '0.01'
          memory: 30M

# Cookies
  demo6:
    container_name: demo6
    build: ./2022/web/6
    environment:
      - PORT=8806
    ports:
      - '8806:80'
    working_dir: /root/task
    stdin_open: true
    tty: true
    dns:
        - 8.8.8.8
        - 1.1.1.1
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 30M
        reservations:
          cpus: '0.01'
          memory: 30M

# Session
  demo7:
    container_name: demo7
    build: ./2022/web/7
    environment:
      - PORT=8807
    ports:
      - '8807:80'
    working_dir: /root/task
    stdin_open: true
    tty: true
    dns:
        - 8.8.8.8
        - 1.1.1.1
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 30M
        reservations:
          cpus: '0.01'
          memory: 30M

# LFI
  demo8:
    container_name: demo8
    build: ./2022/web/8
    environment:
      - PORT=8808
    ports:
      - '8808:80'
    working_dir: /root/task
    stdin_open: true
    tty: true
    dns:
        - 8.8.8.8
        - 1.1.1.1
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 30M
        reservations:
          cpus: '0.01'
          memory: 30M

# Session
  demo11:
    container_name: demo11
    build: ./2022/web/11
    environment:
      - PORT=8811
    ports:
      - '8811:80'
    working_dir: /root/task
    stdin_open: true
    tty: true
    dns:
        - 8.8.8.8
        - 1.1.1.1
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 100M
        reservations:
          cpus: '0.1'
          memory: 100M

